# Generated by Django 6.0.4 on 2026-04-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_inquirytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquirytype',
            name='is_demo',
        ),
        migrations.AddField(
            model_name='inquirytype',
            name='type',
            field=models.CharField(choices=[('1', 'Inbox'), ('2', 'Demo')], default='1', max_length=25),
        ),
    ]
