# Generated by Django 6.0.4 on 2026-04-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_remove_inquirytype_is_demo_inquirytype_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquirytype',
            old_name='type',
            new_name='inquiry_type',
        ),
    ]
