# Generated by Django 6.0.4 on 2026-04-21 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('industrial_ai', 'Industrial AI'), ('ot_it', 'OT + IT'), ('analytics', 'Analytics'), ('vision_ai', 'Vision AI'), ('digitalization', 'Digitalization'), ('transformation', 'Transformation')], max_length=50)),
                ('blog_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('author', models.CharField(max_length=255)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('blog_desc', models.TextField()),
                ('content', models.TextField(help_text='HTML content')),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('meta_desc', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
