# Generated by Django 6.0.4 on 2026-04-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='blogs',
        ),
    ]
