# Generated by Django 6.0.4 on 2026-04-22 12:02

import communication.backend.app
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, validators=[communication.backend.app.validate_email_address])),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number', regex='^\\+?1?\\d{9,15}$')])),
                ('inbox_type', models.CharField(choices=[('contact_form', 'Contact Form'), ('partnership', 'Partnership')], default='contact_form', max_length=20)),
                ('message', models.TextField()),
                ('read_status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inboxes_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inboxes_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inboxes',
                'ordering': ['-date'],
            },
        ),
    ]
