# Generated by Django 6.0.4 on 2026-04-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_inbox_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
