# Generated by Django 6.0.4 on 2026-04-23 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_demorequest'),
        ('masters', '0003_remove_inquirytype_is_demo_inquirytype_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demorequest',
            old_name='name',
            new_name='sender_name',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='inbox_type',
        ),
        migrations.AddField(
            model_name='demorequest',
            name='inquiry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.inquirytype'),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.industrytype'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inquiry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.inquirytype'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
