# Generated by Django 6.0.4 on 2026-04-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_alter_inbox_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='created_by',
        ),
    ]
