# Generated by Django 6.0.4 on 2026-04-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_remove_inbox_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demorequest',
            name='created_by',
        ),
    ]
