# Generated by Django 6.0.4 on 2026-04-22 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('industry', models.CharField(choices=[('steel_and_metals', 'Steel & Metals'), ('energy_and_utilities', 'Energy & Utilities'), ('manufacturing', 'Manufacturing'), ('process_industries', 'Process Industries'), ('safety_and_compliance', 'Safety & Compliance'), ('logistics', 'Logistics'), ('healthcare', 'Healthcare')], max_length=50)),
                ('case_study_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='case_studies/')),
                ('challenges', models.TextField(blank=True, null=True)),
                ('solutions', models.TextField(blank=True, null=True)),
                ('results', models.TextField(blank=True, null=True)),
                ('key_metrics', models.JSONField(blank=True, null=True)),
                ('meta_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'case_studies',
                'ordering': ['-created_at'],
            },
        ),
    ]
