# Generated by Django 6.0.4 on 2026-04-22 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudies',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.industrytype'),
        ),
    ]
