# Generated by Django 6.0.4 on 2026-04-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_text', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('Blog', 'Blog'), ('Case Study', 'Case Study'), ('Inbox', 'Inbox'), ('Demo Request', 'Demo Request')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='New', max_length=50)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
